In [1]:
import glob, os
import numpy as np
import pandas as pd
from tqdm import tqdm_notebook

In [2]:
path = '/home/dev_serverov/Documents/US_stocks/Data/US_stocks_csv'
exchange_list = ['AMEX', 'NASDAQ', 'NYSE', 'NYSE Arca', 'Delisted']

In [3]:
index_list = list(range(1985, 2019))
first_file = True

for exchange in tqdm_notebook(exchange_list, desc = 'exchange loop'):
    all_files = glob.glob(os.path.join(path, exchange, '*.csv'))

    for f in tqdm_notebook(all_files, desc = 'files loop', leave = False):
        df = pd.read_csv(f)
        df['Date'] = pd.to_datetime(df['Date'], format='%Y%m%d', errors='ignore')
        df = df.set_index('Date')
        df['Vol_dol'] = df['Close']*df['Volume']

        col_name = str(df.Ticker[0]) + '_' + exchange

        if first_file:
            df2 = pd.DataFrame(index=index_list, columns = [col_name])
            first_file = False            

        df2[col_name] = 0
        first_year = df.index[0].year
        last__year = df.index[-1].year

        for i in range(first_year, last__year+1):
            df2[col_name][i] = df[str(i)]['Vol_dol'].sum()/250

HBox(children=(IntProgress(value=0, description='exchange loop', max=5, style=ProgressStyle(description_width=…

HBox(children=(IntProgress(value=0, description='files loop', max=318, style=ProgressStyle(description_width='…

HBox(children=(IntProgress(value=0, description='files loop', max=3417, style=ProgressStyle(description_width=…

HBox(children=(IntProgress(value=0, description='files loop', max=3132, style=ProgressStyle(description_width=…

HBox(children=(IntProgress(value=0, description='files loop', max=1858, style=ProgressStyle(description_width=…

HBox(children=(IntProgress(value=0, description='files loop', max=18926, style=ProgressStyle(description_width…

In [7]:
df2.to_csv('/home/dev_serverov/Documents/US_stocks/Data/liquidity_table.csv')

In [4]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 34 entries, 1985 to 2018
Columns: 27651 entries, RIF_AMEX to PNTH-199404_Delisted
dtypes: int64(27651)
memory usage: 7.2 MB

In [5]:
df2.shape

(34, 27651)

In [60]:
df2

,RIF_AMEX,CTEK_AMEX,EVI_AMEX,IAF_AMEX,EIV_AMEX,AE_AMEX,CVR_AMEX,BGSF_AMEX,GSV_AMEX,LTSK_AMEX,...,ENN-200710_Delisted,ZICA-200904_Delisted,MHI-199411_Delisted,MSPD-201312_Delisted,PORT-200307_Delisted,LMED-198910_Delisted,AIK-200402_Delisted,PNTH-199404_Delisted,1e6,5e6
1985,0,0,0,10418,0,15705,16207,0,0,0,...,0,0,0,0,0,1920850,0,0,24,24
1986,0,0,0,179611,0,5974,26896,0,0,0,...,0,0,0,0,0,2776134,0,0,25,25
1987,0,0,0,323687,0,12000,15455,0,0,0,...,0,0,0,0,0,5338605,0,0,26,26
1988,0,0,0,121330,0,4706,15914,0,0,0,...,0,0,0,0,0,4064579,0,0,26,26
1989,0,0,0,189235,0,5088,10913,0,0,0,...,0,0,0,0,0,6915323,0,0,25,25
1990,0,0,673,250468,0,9710,8425,0,0,0,...,0,0,0,0,0,0,0,863,25,25
1991,0,0,1826,153165,0,9100,8325,0,0,0,...,0,0,3217,0,0,0,0,3183,25,25
1992,0,0,529,130115,0,19528,11438,0,0,0,...,0,0,11726,0,0,0,0,7144,26,26
1993,0,0,1821,361931,0,16689,6392,0,0,0,...,0,0,249722,0,0,0,0,214946,28,28
1994,0,0,1326,682697,0,26164,25340,0,0,0,...,872877,6230,283936,0,0,0,57747,283467,30,30
1995,0,0,1380,333407,0,16406,15782,0,0,0,...,646708,416607,0,0,0,0,49797,0,32,32
1996,0,0,1233,441782,0,53581,23891,0,0,0,...,1706837,1095349,0,0,0,0,80468,0,34,34
1997,0,0,673,455767,0,110704,84980,0,0,0,...,2016598,283493,0,0,0,0,85557,0,35,35
1998,0,0,10214,371209,0,45940,55830,0,0,0,...,1923601,375036,0,0,0,0,96400,0,34,34
1999,0,0,9578,317936,0,28140,36938,0,0,0,...,1110159,2843369,0,0,0,0,60738,0,33,33
2000,0,0,44891,183716,0,147394,24442,0,0,0,...,721959,5491469,0,0,598228,0,35160,0,32,32
2001,0,4026,1791,118547,0,53792,11078,0,0,0,...,986173,594258,0,0,848231,0,27432,0,30,30
2002,0,7365,1275,146901,29445,23533,19490,0,0,0,...,857567,368542,0,0,989708,0,23140,0,28,28
2003,0,472,5761,136951,239615,50552,17022,0,0,0,...,834444,241010,0,2149157,1018973,0,37209,0,27,27
2004,0,8411,9860,464947,288308,98659,24786,0,0,0,...,1989199,445534,0,4567572,0,0,3588,0,27,27
2005,0,23932,17153,732944,336553,251742,17107,0,0,0,...,3365081,1243732,0,1850849,0,0,0,0,27,27
2006,130158,8802,11624,641866,308927,541549,25249,0,0,0,...,4858198,299970,0,5302374,0,0,0,0,27,27
2007,425802,13467,9761,1039926,254264,331440,17174,0,0,0,...,12991354,276396,0,2193941,0,0,0,0,28,28
2008,139318,24199,3282,727025,286907,250339,20515,0,0,0,...,0,28897,0,390598,0,0,0,0,28,28
2009,233408,5762,3904,682618,219071,103855,22259,0,0,0,...,0,29941,0,420286,0,0,0,0,27,27
2010,275077,6817,9382,926007,275071,111814,14531,0,0,0,...,0,0,0,4474216,0,0,0,0,27,27
2011,213870,5363,7606,925737,291986,149432,37685,0,0,0,...,0,0,0,3623204,0,0,0,0,28,28
2012,446320,18724,8489,574476,268740,856174,48987,0,155855,0,...,0,0,0,1446709,0,0,0,0,28,28
2013,450127,20413,66009,764431,467409,589066,106363,0,101470,0,...,0,0,0,2815773,0,0,0,0,28,28
2014,325970,27363,76954,604810,314655,618935,118430,5407,77205,0,...,0,0,0,0,0,0,0,0,29,29
2015,489423,17180,28343,418810,324555,390645,231331,28027,59537,0,...,0,0,0,0,0,0,0,0,30,30
2016,612989,12850,153612,362402,417953,165334,81144,1125647,1259339,0,...,0,0,0,0,0,0,0,0,31,31
2017,822598,320623,1002269,366593,397917,210574,67824,409623,1903763,0,...,0,0,0,0,0,0,0,0,31,31
2018,626869,97005,691009,306927,282343,296766,37121,1599758,648963,160837,...,0,0,0,0,0,0,0,0,33,33

In [89]:
df2['1e6'] = 0
for i in range(df2.index[0], df2.index[-1]+1):
    all_tickers = np.array(df2.loc[i])
    mask = ((all_tickers > 0) & (all_tickers< 1e6))
    mask2 = (all_tickers > 0)
    df2['1e6'][i] = all_tickers[mask].size*100/all_tickers[mask2].size
df2['1e6']

1985    86
1986    84
1987    83
1988    86
1989    84
1990    85
1991    81
1992    79
1993    76
1994    77
1995    73
1996    70
1997    67
1998    67
1999    63
2000    59
2001    65
2002    64
2003    60
2004    53
2005    51
2006    48
2007    45
2008    49
2009    53
2010    49
2011    48
2012    50
2013    45
2014    42
2015    44
2016    45
2017    45
2018    45
Name: 1e6, dtype: int64

In [88]:
df2['5e6'] = 0
for i in range(df2.index[0], df2.index[-1]+1):
    all_tickers = np.array(df2.loc[i])
    mask = ((all_tickers > 0) & (all_tickers< 5e6))
    mask2 = (all_tickers > 0)
    df2['5e6'][i] = all_tickers[mask].size*100/all_tickers[mask2].size
df2['5e6']

1985    96
1986    94
1987    94
1988    95
1989    94
1990    95
1991    94
1992    93
1993    91
1994    91
1995    90
1996    88
1997    86
1998    85
1999    82
2000    78
2001    81
2002    80
2003    78
2004    73
2005    71
2006    68
2007    65
2008    68
2009    71
2010    69
2011    68
2012    69
2013    66
2014    64
2015    64
2016    66
2017    66
2018    65
Name: 5e6, dtype: int64

In [97]:
# просто разные цифры для игры

all_tickers = np.array(df2.loc[2018])
mask2 = (all_tickers) > 0 
mask = ((all_tickers > 0) & (all_tickers< 1e6))
sum(mask), sum(mask2), all_tickers[mask].size, all_tickers[mask2].size, sum(all_tickers)

(4149, 9130, 4149, 9130, 351574739512)

In [30]:
# контроль

mask = [(df2.loc[1985]>0) & (df2.loc[1985] < 1e6)]
df2.loc[1985].iloc[mask]

[RIF_AMEX                 False
 CTEK_AMEX                False
 EVI_AMEX                 False
 IAF_AMEX                  True
 EIV_AMEX                 False
 AE_AMEX                   True
 CVR_AMEX                  True
 BGSF_AMEX                False
 GSV_AMEX                 False
 LTSK_AMEX                False
 FSI_AMEX                 False
 SCE-B_AMEX               False
 PTN_AMEX                 False
 SCE-D_AMEX               False
 DSS_AMEX                 False
 AMPE_AMEX                False
 VISI_AMEX                 True
 SRCI_AMEX                False
 LEVB_AMEX                False
 LTSF_AMEX                False
 NNVC_AMEX                False
 SGB_AMEX                 False
 GSS_AMEX                 False
 PCG-H_AMEX               False
 EVBN_AMEX                False
 GLU-A_AMEX               False
 SCE-E_AMEX               False
 NSPR_AMEX                False
 MXC_AMEX                 False
 NXE_AMEX                 False
                          ...
 SVNG-199506_Delisted     False
 FAM-199910_Delisted       True
 PBD-198510_Delisted       True
 BHAG-200408_Delisted     False
 TWFC-200003_Delisted     False
 QEDX-199003_Delisted      True
 KMAGQ-200207_Delisted    False
 PRVT-201607_Delisted     False
 LMCK-201604_Delisted     False
 NWK-201208_Delisted      False
 MTGNY-200402_Delisted    False
 QCFB-200008_Delisted     False
 ALTO-199009_Delisted     False
 DVRFS-199401_Delisted    False
 HAY-198703_Delisted       True
 ATOM-200103_Delisted     False
 CHPP-199602_Delisted     False
 GENS-198602_Delisted     False
 NDM-199412_Delisted      False
 ZSML-201701_Delisted     False
 TDSNA-201201_Delisted    False
 EIC-199710_Delisted       True
 ENN-200710_Delisted      False
 ZICA-200904_Delisted     False
 MHI-199411_Delisted      False
 MSPD-201312_Delisted     False
 PORT-200307_Delisted     False
 LMED-198910_Delisted     False
 AIK-200402_Delisted      False
 PNTH-199404_Delisted     False
 Name: 1985, Length: 27651, dtype: bool]